name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm i

      - name: Generate files
        run: node cli generate-files

      - name: TypeScript check
        run: npx tsc

      - name: ESLint check
        run: npx eslint . --max-warnings=0
